// <auto-generated />
namespace Motorbazar.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class AddNumbersToVehicles : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(AddNumbersToVehicles));
        
        string IMigrationMetadata.Id
        {
            get { return "201902020621131_AddNumbersToVehicles"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
